# Generated by Django 4.0.4 on 2022-06-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
