# Generated by Django 4.0.4 on 2022-06-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
