# Generated by Django 4.0.4 on 2022-06-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
    ]
